//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/CarInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CarInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CarInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CarInput"",
    ""maps"": [
        {
            ""name"": ""Car"",
            ""id"": ""8ebb5754-0417-4f56-a5d7-0ee1ec78af87"",
            ""actions"": [
                {
                    ""name"": ""Turn"",
                    ""type"": ""Value"",
                    ""id"": ""e78ec867-74b7-4815-a57f-ad8637ca553a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accelerating"",
                    ""type"": ""Value"",
                    ""id"": ""d2a06e32-7475-40a2-977b-f22343017899"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c9105e61-cf47-42ab-bc1b-683ec4b8fc71"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""44ede7be-6c95-44e1-9ccb-d691368d57ff"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a12bf023-c86e-42e2-bb20-0693a81d0d97"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""bb4882a0-d9a1-472e-b9eb-f8f3807306c7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""436048cf-bfc5-443c-a9ad-4ebd4f4c18b5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""651b0568-1c3f-4c71-b0b1-7bf76c000806"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""d39f7663-a4f7-450e-8663-091acbe78d87"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5bde7845-d5c3-4d25-a970-0353b45100bc"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2369de8a-5b60-406e-8e83-d4b9ab8e1788"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c4b8205e-5731-40eb-96a2-49936de94493"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""327a330a-cfbc-49ea-900b-71f362a15ae8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerating"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eafc7d7c-20b7-4893-a68b-e20694c13936"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerating"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a7d6e04-4b73-43cc-a5d4-7c9eb39e44c0"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerating"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68c0f757-d2ec-4069-b5f6-79667cfe601f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerating"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BeforeRace"",
            ""id"": ""9a1f0fbc-b477-451b-b53b-afb374ab03a5"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""bc0a37f7-1344-4a41-9bc5-2b0c4e272cdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5253b6c7-2848-4fd9-88e5-11ab1f519064"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3806f617-8f68-4d2a-a096-4b3e7afb5721"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Vide"",
            ""id"": ""8c6ecb63-af95-4416-84e4-4be54336738e"",
            ""actions"": [],
            ""bindings"": []
        },
        {
            ""name"": ""PoseTile"",
            ""id"": ""59f3fc69-d543-4563-bd23-a19cfecafde2"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""b987de2e-1b8c-4961-b319-1e666c358293"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b328ac9b-23d3-4566-8050-8aac244f28c3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""98837dd3-1346-4faa-82e6-b67f352a3871"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d5429a5b-927e-489b-8bbc-a155ef3f695c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4ad465b-eb27-4161-9abe-323fbc746b4a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a7ea671-c675-4be3-90df-773c232e9457"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3481372-1228-4795-a295-567367239cce"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ddd0938-6f6b-40b5-9ca4-64d21f542946"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""Manettes"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bce74f6c-8053-43ed-8fbe-0ba2b3b7e947"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PickTiles"",
            ""id"": ""43999a0b-5c12-470f-9d61-e88a892a60cb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""e6e24e64-e52d-4285-b72f-bd6a39de923a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""2ab95301-4789-4fc2-9086-9684c69fd1e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""079ee07a-7288-4029-88e0-404c47232e29"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""Manettes"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1a9489d-40e2-4a17-95f3-fc8c13da0b94"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68cd81a1-015f-4f5c-822e-6ec781b57d7f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad397afd-1a37-4087-96f7-96f0fc1412a4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""ClavierSouris"",
            ""bindingGroup"": ""ClavierSouris"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Manettes"",
            ""bindingGroup"": ""Manettes"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Car
        m_Car = asset.FindActionMap("Car", throwIfNotFound: true);
        m_Car_Turn = m_Car.FindAction("Turn", throwIfNotFound: true);
        m_Car_Accelerating = m_Car.FindAction("Accelerating", throwIfNotFound: true);
        // BeforeRace
        m_BeforeRace = asset.FindActionMap("BeforeRace", throwIfNotFound: true);
        m_BeforeRace_Newaction = m_BeforeRace.FindAction("New action", throwIfNotFound: true);
        // Vide
        m_Vide = asset.FindActionMap("Vide", throwIfNotFound: true);
        // PoseTile
        m_PoseTile = asset.FindActionMap("PoseTile", throwIfNotFound: true);
        m_PoseTile_Click = m_PoseTile.FindAction("Click", throwIfNotFound: true);
        m_PoseTile_Move = m_PoseTile.FindAction("Move", throwIfNotFound: true);
        m_PoseTile_Rotate = m_PoseTile.FindAction("Rotate", throwIfNotFound: true);
        // PickTiles
        m_PickTiles = asset.FindActionMap("PickTiles", throwIfNotFound: true);
        m_PickTiles_Move = m_PickTiles.FindAction("Move", throwIfNotFound: true);
        m_PickTiles_Click = m_PickTiles.FindAction("Click", throwIfNotFound: true);
    }

    ~@CarInput()
    {
        UnityEngine.Debug.Assert(!m_Car.enabled, "This will cause a leak and performance issues, CarInput.Car.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_BeforeRace.enabled, "This will cause a leak and performance issues, CarInput.BeforeRace.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Vide.enabled, "This will cause a leak and performance issues, CarInput.Vide.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PoseTile.enabled, "This will cause a leak and performance issues, CarInput.PoseTile.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PickTiles.enabled, "This will cause a leak and performance issues, CarInput.PickTiles.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Car
    private readonly InputActionMap m_Car;
    private List<ICarActions> m_CarActionsCallbackInterfaces = new List<ICarActions>();
    private readonly InputAction m_Car_Turn;
    private readonly InputAction m_Car_Accelerating;
    public struct CarActions
    {
        private @CarInput m_Wrapper;
        public CarActions(@CarInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Turn => m_Wrapper.m_Car_Turn;
        public InputAction @Accelerating => m_Wrapper.m_Car_Accelerating;
        public InputActionMap Get() { return m_Wrapper.m_Car; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarActions set) { return set.Get(); }
        public void AddCallbacks(ICarActions instance)
        {
            if (instance == null || m_Wrapper.m_CarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarActionsCallbackInterfaces.Add(instance);
            @Turn.started += instance.OnTurn;
            @Turn.performed += instance.OnTurn;
            @Turn.canceled += instance.OnTurn;
            @Accelerating.started += instance.OnAccelerating;
            @Accelerating.performed += instance.OnAccelerating;
            @Accelerating.canceled += instance.OnAccelerating;
        }

        private void UnregisterCallbacks(ICarActions instance)
        {
            @Turn.started -= instance.OnTurn;
            @Turn.performed -= instance.OnTurn;
            @Turn.canceled -= instance.OnTurn;
            @Accelerating.started -= instance.OnAccelerating;
            @Accelerating.performed -= instance.OnAccelerating;
            @Accelerating.canceled -= instance.OnAccelerating;
        }

        public void RemoveCallbacks(ICarActions instance)
        {
            if (m_Wrapper.m_CarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICarActions instance)
        {
            foreach (var item in m_Wrapper.m_CarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CarActions @Car => new CarActions(this);

    // BeforeRace
    private readonly InputActionMap m_BeforeRace;
    private List<IBeforeRaceActions> m_BeforeRaceActionsCallbackInterfaces = new List<IBeforeRaceActions>();
    private readonly InputAction m_BeforeRace_Newaction;
    public struct BeforeRaceActions
    {
        private @CarInput m_Wrapper;
        public BeforeRaceActions(@CarInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_BeforeRace_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_BeforeRace; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BeforeRaceActions set) { return set.Get(); }
        public void AddCallbacks(IBeforeRaceActions instance)
        {
            if (instance == null || m_Wrapper.m_BeforeRaceActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BeforeRaceActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IBeforeRaceActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IBeforeRaceActions instance)
        {
            if (m_Wrapper.m_BeforeRaceActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBeforeRaceActions instance)
        {
            foreach (var item in m_Wrapper.m_BeforeRaceActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BeforeRaceActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BeforeRaceActions @BeforeRace => new BeforeRaceActions(this);

    // Vide
    private readonly InputActionMap m_Vide;
    private List<IVideActions> m_VideActionsCallbackInterfaces = new List<IVideActions>();
    public struct VideActions
    {
        private @CarInput m_Wrapper;
        public VideActions(@CarInput wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_Vide; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VideActions set) { return set.Get(); }
        public void AddCallbacks(IVideActions instance)
        {
            if (instance == null || m_Wrapper.m_VideActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VideActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(IVideActions instance)
        {
        }

        public void RemoveCallbacks(IVideActions instance)
        {
            if (m_Wrapper.m_VideActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVideActions instance)
        {
            foreach (var item in m_Wrapper.m_VideActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VideActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VideActions @Vide => new VideActions(this);

    // PoseTile
    private readonly InputActionMap m_PoseTile;
    private List<IPoseTileActions> m_PoseTileActionsCallbackInterfaces = new List<IPoseTileActions>();
    private readonly InputAction m_PoseTile_Click;
    private readonly InputAction m_PoseTile_Move;
    private readonly InputAction m_PoseTile_Rotate;
    public struct PoseTileActions
    {
        private @CarInput m_Wrapper;
        public PoseTileActions(@CarInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_PoseTile_Click;
        public InputAction @Move => m_Wrapper.m_PoseTile_Move;
        public InputAction @Rotate => m_Wrapper.m_PoseTile_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_PoseTile; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PoseTileActions set) { return set.Get(); }
        public void AddCallbacks(IPoseTileActions instance)
        {
            if (instance == null || m_Wrapper.m_PoseTileActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PoseTileActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
        }

        private void UnregisterCallbacks(IPoseTileActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
        }

        public void RemoveCallbacks(IPoseTileActions instance)
        {
            if (m_Wrapper.m_PoseTileActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPoseTileActions instance)
        {
            foreach (var item in m_Wrapper.m_PoseTileActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PoseTileActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PoseTileActions @PoseTile => new PoseTileActions(this);

    // PickTiles
    private readonly InputActionMap m_PickTiles;
    private List<IPickTilesActions> m_PickTilesActionsCallbackInterfaces = new List<IPickTilesActions>();
    private readonly InputAction m_PickTiles_Move;
    private readonly InputAction m_PickTiles_Click;
    public struct PickTilesActions
    {
        private @CarInput m_Wrapper;
        public PickTilesActions(@CarInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PickTiles_Move;
        public InputAction @Click => m_Wrapper.m_PickTiles_Click;
        public InputActionMap Get() { return m_Wrapper.m_PickTiles; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PickTilesActions set) { return set.Get(); }
        public void AddCallbacks(IPickTilesActions instance)
        {
            if (instance == null || m_Wrapper.m_PickTilesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PickTilesActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IPickTilesActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IPickTilesActions instance)
        {
            if (m_Wrapper.m_PickTilesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPickTilesActions instance)
        {
            foreach (var item in m_Wrapper.m_PickTilesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PickTilesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PickTilesActions @PickTiles => new PickTilesActions(this);
    private int m_ClavierSourisSchemeIndex = -1;
    public InputControlScheme ClavierSourisScheme
    {
        get
        {
            if (m_ClavierSourisSchemeIndex == -1) m_ClavierSourisSchemeIndex = asset.FindControlSchemeIndex("ClavierSouris");
            return asset.controlSchemes[m_ClavierSourisSchemeIndex];
        }
    }
    private int m_ManettesSchemeIndex = -1;
    public InputControlScheme ManettesScheme
    {
        get
        {
            if (m_ManettesSchemeIndex == -1) m_ManettesSchemeIndex = asset.FindControlSchemeIndex("Manettes");
            return asset.controlSchemes[m_ManettesSchemeIndex];
        }
    }
    public interface ICarActions
    {
        void OnTurn(InputAction.CallbackContext context);
        void OnAccelerating(InputAction.CallbackContext context);
    }
    public interface IBeforeRaceActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IVideActions
    {
    }
    public interface IPoseTileActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
    }
    public interface IPickTilesActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
    }
}
